### ISSUE TITLE
Hiding/Unhiding columns misplaces tooltip

### ISSUE THREAD

**Issue by caiocaminoski** [sebastiengunther/EasyTableTooltip#1]
Hello! First of all, great extension! Thank you very much.

Unfortunately, we realize that every time we hide or show one column from the table the tooltip gets misplaced. It is necessary to refresh the page to get it correctly placed again. 

Is there a way to avoid this problem?

Thank you in advance.

Caio

**Comment by sebastiengunther** [comment]
Hello,

Thank you for your feedback.
When the extension is loaded before the table, if the position of the columns was changed, it was not taken into account.
I fixed this problem, now you can display/hide/modify the order of the columns.

Regards,
Sébastien

**Comment by caiocaminoski** [comment]
Thank you very much!

I will test it out!

Cheers,

Caio
